sonata_user_security:
    resource: "@RzUserBundle/Resources/config/routing/security.xml"

sonata_user_resetting:
    resource: "@RzUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@RzUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

sonata_user_register:
    resource: "@RzUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@RzUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
    prefix: /

fos_oauth_server_authorize:
    resource: "@RzOAuthServerBundle/Resources/config/routing/authorize.xml"
    prefix: /

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
    prefix: /

sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /page

sonata_media_media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

#fos_comment:
#    type: rest
#    resource: "@FOSCommentBundle/Resources/config/routing.yml"
#    prefix: /comments
#    defaults: { _format: html }

rz_search:
    resource: "@RzSearchBundle/Resources/config/routing/search.xml"
    prefix: /search

# to make sure that ajax controllers are filtered and are not added to page
# you need to add the prefix to ignore_uri_patterns
rz_search_helper:
    resource: "@RzSearchBundle/Resources/config/routing/helper.xml"
    prefix: /helper