##############################################################################
# Sonata News
# more information can be found here https://sonata-project.org/bundles/news
##############################################################################
sonata_news:
    class:
        post:       AppBundle\Entity\News\Post
        comment:    AppBundle\Entity\News\Comment
        tag:        AppBundle\Entity\Classification\Tag
        collection: AppBundle\Entity\Classification\Collection
        user:       AppBundle\Entity\User\User
        media:      AppBundle\Entity\Media\Media

    admin:
        post:
            class:        AppBundle\Admin\News\PostAdmin
            controller:   RzNewsBundle:PostAdmin

    title:        %sonata_news.blog_title%
    link:         %sonata_news.blog_link%
    description:  %sonata_news.blog_description%
    salt:         %sonata_news.salt%

    # permalink_generator: sonata.news.permalink.category # /party/new-year
    permalink_generator: sonata.news.permalink.date # /2011/12/31/new-year

    # comment options
    comment:
        notification:
            emails:   %sonata_news.comment.emails%
            from:     %sonata_news.comment.email_from%
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

##############################################################################
# News Doctrine
# Enable Doctrine to map the provided entities
##############################################################################
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataNewsBundle: ~


###############################################################################
# RzNews
###############################################################################
rz_news:
  manager_class:
    orm:
      post:       'Rz\NewsBundle\Entity\PostManager'

  #=====================================================================
  # Required Default Settings
  #=====================================================================
  slugify_service: 'sonata.core.slugify.cocur' # slugify service for context & collection NOTE: sonata.core.slugify.native is already depricated

  #=====================================================================
  # TO BE USED ON A FULL CUSTOMIZED CMS
  #   (old way of implemeting NEWS BUNDLE)
  #   NOTE: ALL CONTROLLERS SHOULD BE IMPLEMENTED ON THE AppBundle LEVEL
  #=====================================================================
  #enable_controller: false #should be set at the start of the project. If set to false all post/news will generate pages

  #=====================================================================
  # PROVIDERS Configuration
  #   provider are classes that allows programatically adding
  #   new fields on the POST table
  #=====================================================================
  providers:
    #----------------------------------------------------------------------------------------
    # Post Provider
    #----------------------------------------------------------------------------------------
    post:
      #----------------------------------------------------------------------------------------
      # Use context ID from ClassificationBundle
      #----------------------------------------------------------------------------------------
      default_context: 'news' # NOTE: default context used for grouping tag, media, ckeditor_context, collection
      default_collection: 'acticle' # NOTE: default collection used for grouping provider type
      default_provider_collection: acticle # NOTE: default provider - provider are classes that allows programatically adding new fields on the POST table
      #----------------------------------------------------------------------------------------
      # use the collection description or slug for collections configuration ID it will be automatically slugified
      #----------------------------------------------------------------------------------------
      collections:
          default:  # the default collection is mandatory (fallback provider when no other provider is set)
              provider: rz.news.post.provider.default
              #----------------------------------------------------------------------------------------
              # NOTE! default template should be present on post_block_service template list
              #       preferred_template will be the prefered choice for template selection
              #----------------------------------------------------------------------------------------
              preferred_template: RzNewsBundle:Block:block_post_default.html.twig
          acticle:
              provider: rz.news.post.provider.default
              preferred_template: RzNewsBundle:Block:block_post.html.twig

    #----------------------------------------------------------------------------------------
    # Post Sets Provider
    #----------------------------------------------------------------------------------------
    post_sets:
      #----------------------------------------------------------------------------------------
      # Use context ID from ClassificationBundle
      #----------------------------------------------------------------------------------------
      default_context: post-sets
      default_collection: default
      default_provider_collection: default # NOTE: default provider - provider are classes that allows programatically adding new fields on the POST table
      #default settings for PostSetsHasPost lookup.
      post_lookup_settings:
        default_collection: article
        hide_collection: true
      #optional
      collections:
            default:
                # optional
                post_sets:
                  provider: rz.news.post_sets.provider.default
                  #----------------------------------------------------------------------------------------
                  # Optional! if provider is set and no lookup collection post_lookup_settings.collection
                  #           will automcatically set as post_lookup_settings.collection.
                  #----------------------------------------------------------------------------------------
                  post_lookup_settings: ~
                    #collection: article
                    #hide_collection: true
                # optional
                post_sets_has_posts:
                  provider: ~ # rz.news.post_sets_has_posts.provider.default

    #----------------------------------------------------------------------------------------
    # SEO Provider
    #----------------------------------------------------------------------------------------
    seo:
      default_provider: rz.news.provider.seo.default #NOTE: default seo provider additional fields for SEO

  #=====================================================================
  # Default permalink
  #   permalinks services generates SEO friendly URL for post
  #   requires 2 permalinks article URL and category URL eg.
  #   article URL: /article/article-slug ---> canonical URL
  #   category URL /category1/sub-category/article-slug ---> duplicate URL
  #=====================================================================
  permalink:
    default_permalink: default
    default_category_permalink: category_default
    #=====================================================================
    # News Permalink Configuration
    # define several permalink generators
    #=====================================================================
    permalinks:
        default:  # the default permalink is mandatory
            permalink: rz.news.permalink.default
        category_default:  # the default category permalink is mandatory
            permalink: rz.news.permalink.category
        slug:  # optional permalik can replace default
            permalink: rz.news.permalink.slug

  #=====================================================================
  # News Page Settings
  #   1. Transformer class to generate A page for a certain POST
  #=====================================================================
  news_page:
    #=====================================================================
    # News Page Post Block Service Settings (Default Values)
    #=====================================================================
    post_block_service: rz.news.news_page.default.block.post #block service to be used when creating post page
    default_post_block_template: #default template if no template is set on rz.news.news_page.block.post
      name: Default
      template: RzNewsBundle:Block:block_post_default.html.twig
    news_page_parent_slug: 'articles'
    transformer:
      class:      'Rz\NewsBundle\Entity\Transformer'
    page_templates:
      default:
        name: 'Default'
        template_code: 'default'