#
# more information can be found here https://sonata-project.org/bundles/admin
#
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    options:
        html5_validate: false # does not use html5 validation
        pager_links:    5        # pager max links to display
        use_bootlint:   %kernel.debug%
        use_select2:    true
        use_icheck:     true

    dashboard:
        blocks:
            #- { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
            -
                class:    col-lg-6 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code: sonata.news.admin.comment
                    icon: fa-comments
                    text: Open Comment
                    filters:
                        status: { type: 3, value: 0 } # 3 => NumberType::TYPE_EQUAL
            -
                class:    col-lg-6 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code:  sonata.page.admin.page
                    icon:  fa-magic
                    text:  Edited Pages
                    color: bg-yellow
                    filters:
                        edited: { value: 1 }

            - { class:    col-lg-12 col-xs-12 , roles: [ROLE_SUPER_ADMIN], position: top, type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'><h3 class='panel-title'>Montage</h3></div><div class='panel-body'>Welcome to Montage Admin! Montage is an open source content management platform based on Sonata Project!</div></div>"} }
            - { position: left, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 25 }}
            - { position: left, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 7, mode: admin }}
            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: https://sonata-project.org/blog/archive.rss, template: SonataAdminBundle:Block:block_rss_dashboard.html.twig }}



        groups:
            sonata.admin.group.content:
                label:           sonata_content
                label_catalogue: SonataDemoBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - sonata.news.admin.comment
                    - sonata.news.admin.post
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
                    - sonata.comment.admin.thread

            sonata.admin.group.classification:
                label:           sonata_classification
                label_catalogue: SonataClassificationBundle
                icon:            '<i class="fa fa-tags"></i>'
                items:
                    - sonata.classification.admin.category
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection
                    - sonata.classification.admin.context

            sonata.admin.group.site_builder:
                label:           Site Builder
                label_catalogue: SonataDemoBundle
                icon:            '<i class="fa fa-puzzle-piece"></i>'
                items:
                    - sonata.page.admin.page
                    - sonata.page.admin.site

            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - sonata.page.admin.site
                    - sonata.notification.admin.message

            sonata.admin.group.demo:
                label: Demo
                icon:  '<i class="fa fa-play-circle"></i>'
                items:
                    - sonata.demo.admin.car
                    - sonata.demo.admin.engine
                    - sonata.demo.admin.color
                    - sonata.demo.admin.material

    templates:
        user_block:                   'SonataUserBundle:Admin\Core:user_block.html.twig'
        add_block:                    'SonataAdminBundle:Core:add_block.html.twig'
        layout:                       'RzAdminBundle::standard_layout.html.twig'
        ajax:                         'SonataAdminBundle::ajax_layout.html.twig'
        dashboard:                    'SonataAdminBundle:Core:dashboard.html.twig'
        search:                       'SonataAdminBundle:Core:search.html.twig'
        list:                         'RzAdminBundle:CRUD:list.html.twig'
        filter:                       'SonataAdminBundle:Form:filter_admin_fields.html.twig'
        show:                         'SonataAdminBundle:CRUD:show.html.twig'
        show_compare:                 'SonataAdminBundle:CRUD:show_compare.html.twig'
        edit:                         'SonataAdminBundle:CRUD:edit.html.twig'
        preview:                      'SonataAdminBundle:CRUD:preview.html.twig'
        history:                      'SonataAdminBundle:CRUD:history.html.twig'
        acl:                          'SonataAdminBundle:CRUD:acl.html.twig'
        history_revision_timestamp:   'SonataAdminBundle:CRUD:history_revision_timestamp.html.twig'
        action:                       'SonataAdminBundle:CRUD:action.html.twig'
        select:                       'SonataAdminBundle:CRUD:list__select.html.twig'
        list_block:                   'SonataAdminBundle:Block:block_admin_list.html.twig'
        search_result_block:          'SonataAdminBundle:Block:block_search_result.html.twig'
        short_object_description:     'SonataAdminBundle:Helper:short-object-description.html.twig'
        delete:                       'SonataAdminBundle:CRUD:delete.html.twig'
        batch:                        'SonataAdminBundle:CRUD:list__batch.html.twig'
        batch_confirmation:           'SonataAdminBundle:CRUD:batch_confirmation.html.twig'
        inner_list_row:               'SonataAdminBundle:CRUD:list_inner_row.html.twig'
        outer_list_rows_mosaic:       'RzAdminBundle:CRUD:list_outer_rows_mosaic.html.twig'
        outer_list_rows_list:         'SonataAdminBundle:CRUD:list_outer_rows_list.html.twig'
        outer_list_rows_tree:         'SonataAdminBundle:CRUD:list_outer_rows_tree.html.twig'
        base_list_field:              'RzAdminBundle:CRUD:base_list_field.html.twig'
        pager_links:                  'RzAdminBundle:Pager:links.html.twig'
        pager_results:                'RzAdminBundle:Pager:results.html.twig'
        tab_menu_template:            'SonataAdminBundle:Core:tab_menu_template.html.twig'
        knp_menu_template:            'SonataAdminBundle:Menu:sonata_menu.html.twig'

    assets:
        stylesheets:
            # The sandbox includes default pre-optimized version of some css and js
            # So you can either use them, and add your custom assets here
            #   ~ or ~
            # tweak the assetic.yml and the following lines
            - assetic/sonata_admin_css.css
            - assetic/sonata_formatter_css.css
            - assetic/sonata_jqueryui_css.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css


        javascripts:
            - assetic/sonata_admin_js.js
            - assetic/sonata_jqueryui_js.js
            - assetic/sonata_formatter_js.js
            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js



sonata_doctrine_orm_admin:
    templates:
      types:
        list:
          string:   'RzAdminBundle:CRUD:list_string.html.twig'
