##############################################################################
# Sonata Admin
#   more information can be found here https://sonata-project.org/bundles/admin
##############################################################################
sonata_admin:
    # default value, change it to sonata.admin.security.handler.acl to use ACL
    security:
        handler: sonata.admin.security.handler.acl
        # acl security information
        information:
            GUEST:    [VIEW, LIST]
            STAFF:    [EDIT, LIST, CREATE]
            EDITOR:   [OPERATOR, EXPORT]
            ADMIN:    [MASTER]
        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]
        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]

    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    options:
        html5_validate: false # does not use html5 validation
        pager_links:    5        # pager max links to display
        use_bootlint:   %kernel.debug%
        use_select2:    true
        use_icheck:     true
        use_stickyforms:      true

    dashboard:
        blocks:
            #- { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.admin_doctrine_orm.block.audit}
#            -
#                class:    col-lg-6 col-xs-6
#                position: top
#                type:     sonata.admin.block.stats
#                settings:
#                    code: sonata.news.admin.comment
#                    icon: fa-comments
#                    text: Open Comment
#                    filters:
#                        status: { type: 3, value: 0 } # 3 => NumberType::TYPE_EQUAL
            -
                class:    col-lg-6 col-xs-6
                position: top
                type:     sonata.admin.block.stats
                settings:
                    code:  sonata.page.admin.page
                    icon:  fa-magic
                    text:  Edited Pages
                    color: bg-yellow
                    filters:
                        edited: { value: 1 }

            - { class:    col-lg-12 col-xs-12 , roles: [ROLE_SUPER_ADMIN], position: top, type: sonata.block.service.text, settings: { content: "<div class='panel panel-default'><div class='panel-heading'><h3 class='panel-title'>Montage</h3></div><div class='panel-body'>Welcome to Montage Admin! Montage is an open source content management platform based on Sonata Project!</div></div>"} }
            - { position: left, type: sonata.timeline.block.timeline, settings: { context: SONATA_ADMIN, max_per_page: 25 }}
            - { position: left, type: sonata.news.block.recent_posts, settings: { title: Recent Posts, number: 7, mode: admin }}
            - { position: right, type: sonata.block.service.rss, settings: { title: Sonata Project's Feeds, url: https://sonata-project.org/blog/archive.rss, template: SonataAdminBundle:Block:block_rss_dashboard.html.twig }}



        groups:
            sonata.admin.group.content:
                label:           sonata_content
                label_catalogue: SonataPageBundle
                icon:            '<i class="fa fa-th"></i>'
                items:
                    - sonata.news.admin.post
                    - rz.news.admin.post_sets
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
                    - sonata.comment.admin.thread

            sonata.admin.group.classification:
                label:           sonata_classification
                label_catalogue: SonataClassificationBundle
                icon:            '<i class="fa fa-tags"></i>'
                items:
                    - sonata.classification.admin.category
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.collection
                    - sonata.classification.admin.context

            sonata.admin.group.site_builder:
                label:           Site Builder
                label_catalogue: SonataDemoBundle
                icon:            '<i class="fa fa-puzzle-piece"></i>'
                items:
                    - sonata.page.admin.page
                    - sonata.page.admin.shared_block
                    - sonata.page.admin.site
                    - rz.redirect.admin.redirect

            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group
                    - sonata.page.admin.site
                    - sonata.notification.admin.message

            sonata.admin.group.demo:
                label: Demo
                icon:  '<i class="fa fa-play-circle"></i>'
                items:
                    - sonata.demo.admin.car
                    - sonata.demo.admin.engine
                    - sonata.demo.admin.color
                    - sonata.demo.admin.material

    templates:
        user_block:                   'SonataUserBundle:Admin\Core:user_block.html.twig'
        add_block:                    'SonataAdminBundle:Core:add_block.html.twig'
        layout:                       'RzAdminBundle::standard_layout.html.twig'
        ajax:                         'SonataAdminBundle::ajax_layout.html.twig'
        dashboard:                    'SonataAdminBundle:Core:dashboard.html.twig'
        search:                       'SonataAdminBundle:Core:search.html.twig'
        list:                         'RzAdminBundle:CRUD:list.html.twig'
        filter:                       'SonataAdminBundle:Form:filter_admin_fields.html.twig'
        show:                         'SonataAdminBundle:CRUD:show.html.twig'
        show_compare:                 'SonataAdminBundle:CRUD:show_compare.html.twig'
        edit:                         'RzAdminBundle:CRUD:edit.html.twig'
        preview:                      'SonataAdminBundle:CRUD:preview.html.twig'
        history:                      'SonataAdminBundle:CRUD:history.html.twig'
        acl:                          'SonataAdminBundle:CRUD:acl.html.twig'
        history_revision_timestamp:   'SonataAdminBundle:CRUD:history_revision_timestamp.html.twig'
        action:                       'SonataAdminBundle:CRUD:action.html.twig'
        select:                       'RzAdminBundle:CRUD:list__select.html.twig'
        list_block:                   'SonataAdminBundle:Block:block_admin_list.html.twig'
        search_result_block:          'SonataAdminBundle:Block:block_search_result.html.twig'
        short_object_description:     'SonataAdminBundle:Helper:short-object-description.html.twig'
        delete:                       'SonataAdminBundle:CRUD:delete.html.twig'
        batch:                        'RzAdminBundle:CRUD:list__batch.html.twig'
        batch_confirmation:           'SonataAdminBundle:CRUD:batch_confirmation.html.twig'
        inner_list_row:               'SonataAdminBundle:CRUD:list_inner_row.html.twig'
        outer_list_rows_mosaic:       'RzAdminBundle:CRUD:list_outer_rows_mosaic.html.twig'
        outer_list_rows_list:         'SonataAdminBundle:CRUD:list_outer_rows_list.html.twig'
        outer_list_rows_tree:         'SonataAdminBundle:CRUD:list_outer_rows_tree.html.twig'
        base_list_field:              'RzAdminBundle:CRUD:base_list_field.html.twig'
        pager_links:                  'RzAdminBundle:Pager:links.html.twig'
        pager_results:                'RzAdminBundle:Pager:results.html.twig'
        tab_menu_template:            'SonataAdminBundle:Core:tab_menu_template.html.twig'
        knp_menu_template:            'SonataAdminBundle:Menu:sonata_menu.html.twig'

    assets:
        stylesheets:
            # The sandbox includes default pre-optimized version of some css and js
            # So you can either use them, and add your custom assets here
            #   ~ or ~
            # tweak the assetic.yml and the following lines
            - assetic/sonata_admin_css.css
            - assetic/sonata_formatter_css.css
            - assetic/sonata_jqueryui_css.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css


        javascripts:
            - assetic/sonata_admin_js.js
            - assetic/sonata_jqueryui_js.js
            - assetic/sonata_formatter_js.js
            - bundles/sonataformatter/vendor/ckeditor/ckeditor.js

#    extensions:
#        app.admin.extension.user:
#            admins:
#                - sonata.user.admin.user

    admin_services:
        #override admin templates
        sonata.user.admin.user:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    list:                     'RzUserBundle:CRUD:list.html.twig'
                    outer_list_rows_mosaic:   'RzUserBundle:CRUD:list_outer_rows_mosaic_user.html.twig'

        sonata.user.admin.group:
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    outer_list_rows_mosaic:   'RzUserBundle:CRUD:list_outer_rows_mosaic_group.html.twig'

        sonata.classification.admin.category:
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    list:                     'RzClassificationBundle:CategoryAdmin:list.html.twig'
                    outer_list_rows_mosaic:   'RzClassificationBundle:CategoryAdmin:list_outer_rows_mosaic.html.twig'

        sonata.classification.admin.collection:
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    #Tabbed Version
                    #list:                     'RzClassificationBundle:CollectionAdmin:list.html.twig'
                    #Side menu version
                    list:                     'RzClassificationBundle:CollectionAdmin:list_alt.html.twig'
                    outer_list_rows_mosaic:   'RzClassificationBundle:CollectionAdmin:list_outer_rows_mosaic.html.twig'

        sonata.classification.admin.tag:
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    #Tabbed Version
                    #list:                     'RzClassificationBundle:TagAdmin:list.html.twig'
                    #Side menu version
                    list:                     'RzClassificationBundle:TagAdmin:list_alt.html.twig'
                    outer_list_rows_mosaic:   'RzClassificationBundle:TagAdmin:list_outer_rows_mosaic.html.twig'

        sonata.classification.admin.context:
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    outer_list_rows_mosaic:   'RzClassificationBundle:ContextAdmin:list_outer_rows_mosaic.html.twig'

        sonata.news.admin.post:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    #Tabbed Version
                    #list:                     'RzNewsBundle:PostAdmin:list.html.twig'
                    #Side menu version
                    list:                     'RzNewsPageBundle:PostAdmin:list_alt.html.twig'
                    outer_list_rows_mosaic:   'RzNewsBundle:PostAdmin:list_outer_rows_mosaic.html.twig'
                    edit:                     'RzNewsPageBundle:PostAdmin:edit.html.twig'

        sonata.media.admin.media:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    list:                     'RzMediaBundle:MediaAdmin:list.html.twig'
                    edit:                     'RzMediaBundle:MediaAdmin:edit.html.twig'
                    outer_list_rows_mosaic:   'RzMediaBundle:MediaAdmin:list_outer_rows_mosaic.html.twig'
                    # required override of RzMediaBundle
                    inner_list_row:           'SonataAdminBundle:CRUD:list_inner_row.html.twig'
                    base_list_field:          'RzAdminBundle:CRUD:base_list_field.html.twig'

        sonata.media.admin.gallery:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    #Tabbed Version
                    #list:                     'RzMediaBundle:GalleryAdmin:list.html.twig'
                    #Side menu version
                    list:                     'RzMediaBundle:GalleryAdmin:list_alt.html.twig'
                    outer_list_rows_mosaic:   'RzMediaBundle:GalleryAdmin:list_outer_rows_mosaic.html.twig'

        sonata.comment.admin.thread:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    outer_list_rows_mosaic:   'RzCommentBundle:ThreadAdmin:list_outer_rows_mosaic.html.twig'

        sonata.comment.admin.comment:
            pager_type:  simple
            label:       comment
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    list:                     'RzCommentBundle:CommentAdmin:list.html.twig'
                    outer_list_rows_mosaic:   'RzCommentBundle:CommentAdmin:list_outer_rows_mosaic.html.twig'

        sonata.page.admin.page:
            pager_type:  simple
            templates:
                # required form override of
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    list:                     'RzPageBundle:PageAdmin:list.html.twig'
                    outer_list_rows_mosaic:   'RzPageBundle:PageAdmin:list_outer_rows_mosaic.html.twig'

        sonata.page.admin.block:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    outer_list_rows_mosaic:   'RzPageBundle:BlockAdmin:list_outer_rows_mosaic.html.twig'

        sonata.page.admin.shared_block:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    outer_list_rows_mosaic:   'RzPageBundle:BlockAdmin:list_outer_rows_mosaic.html.twig'

        sonata.page.admin.snapshot:
            pager_type:  simple
            templates:
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'

        sonata.page.admin.site:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    outer_list_rows_mosaic:   'RzPageBundle:SiteAdmin:list_outer_rows_mosaic.html.twig'

        rz.news.admin.post_has_category:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    #Tabbed Version
                    #list:                     'RzNewsBundle:PostHasCategoryAdmin:list.html.twig'
                    #Side menu version
                    list:                     'RzNewsPageBundle:PostHasCategoryAdmin:list_alt.html.twig'
                    outer_list_rows_mosaic:   'RzNewsBundle:PostHasCategoryAdmin:list_outer_rows_mosaic.html.twig'

        rz.news.admin.post_sets:
            pager_type:  simple
            templates:
                # required form override of RzDoctrineORMAdminBundle
                form:
                  - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
                view:
                    #Tabbed Version
                    #list:                     'RzNewsBundle:PostSetsAdmin:list.html.twig'
                    #Side menu version
                    list:                     'RzNewsBundle:PostSetsAdmin:list_alt.html.twig'
                    outer_list_rows_mosaic:   'RzNewsBundle:PostSetsAdmin:list_outer_rows_mosaic.html.twig'

##############################################################################
# Sonata Doctrine ORM
# sonata doctrine ORM bundle configuration
##############################################################################
sonata_doctrine_orm_admin:
    templates:
      form:
        - 'RzDoctrineORMAdminBundle:Form:form_admin_fields.html.twig'
      filter:
        - RzDoctrineORMAdminBundle:Form:filter_admin_fields.html.twig
      types:
        list:
          string:   'RzAdminBundle:CRUD:list_string.html.twig'

##############################################################################
# Sonata Doctrine MongoDB
##############################################################################
# sonata doctrine MongoDB bundle configuration
#sonata_doctrine_mongo_db_admin:

##############################################################################
# RZ Admin
##############################################################################
rz_admin:
  options:
    use_footable: true
  pool:
    base_admin_class: Rz\AdminBundle\Admin\Pool

