##############################################################################
# Sonata Media
# more information can be found here https://sonata-project.org/bundles/media
##############################################################################
sonata_media:
    class:
        media:             AppBundle\Entity\Media\Media
        gallery:           AppBundle\Entity\Media\Gallery
        gallery_has_media: AppBundle\Entity\Media\GalleryHasMedia
        category:          AppBundle\Entity\Classification\Category

    db_driver:       doctrine_orm # | doctrine_mongodb
    default_context: default
    contexts:
        default:  # the default context is mandatory
            download:
                mode: http # X-Sendfile | http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100, quality: 100}
                big:   { width: 970 , quality: 100}

        news:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.vimeo

            formats:
                abstract: { width: 100, quality: 100}
                wide:     { width: 820, quality: 100}

        sonata_collection:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

    cdn:
        # define the public base url for the uploaded media
        server:
            path:      %sonata_media.cdn.host%

    filesystem:
        # define where the uploaded file will be stored
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

    providers:
        # ...
        file:
            # the resizer must be set to false, otherwhise this can delete icon files from the fs
            resizer:    false
            allowed_extensions: ['pdf', 'txt', 'rtf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pttx', 'odt', 'odg', 'odp', 'ods', 'odc', 'odf', 'odb', 'csv', 'xml', 'zip']
            allowed_mime_types:
              - 'application/pdf'
              - 'application/x-pdf'
              - 'application/rtf'
              - 'text/html'
              - 'text/rtf'
              - 'text/plain'
              - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
              - 'application/vnd.openxmlformats-officedocument.spreadsheetml.template'
              - 'application/vnd.openxmlformats-officedocument.presentationml.template'
              - 'application/vnd.openxmlformats-officedocument.presentationml.slideshow'
              - 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
              - 'application/vnd.openxmlformats-officedocument.presentationml.slide'
              - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
              - 'application/vnd.openxmlformats-officedocument.wordprocessingml.template'
              - 'application/vnd.ms-excel.addin.macroEnabled.12'
              - 'application/vnd.ms-excel.sheet.binary.macroEnabled.12'
              - 'application/zip'

        image:
           thumbnail: sonata.media.thumbnail.format          # default value
        vimeo:
            thumbnail: sonata.media.thumbnail.format          # default value
        youtube:
            thumbnail: sonata.media.thumbnail.format          # default value
        dailymotion:
            thumbnail: sonata.media.thumbnail.format          # default value


    pixlr:
        enabled:  true
        referrer: Demo - Sonata Project

    resizer:
        simple:
            mode:  inset

##############################################################################
# Media Doctrine
# Enable Doctrine to map the provided entities
##############################################################################
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~



##############################################################################
# Rz Media
##############################################################################
rz_media:
  #==================================================================
  # DEFAULT VALUE -- OLNY REQUIRED IF TOP BUNDLE IS NOT APPBUNDLE
  #==================================================================

  #class:
  #    media:               AppBundle\Entity\Media\Media
  #    gallery:             AppBundle\Entity\Media\Gallery
  #    gallery_has_media:   AppBundle\Entity\Media\GalleryHasMedia
  #    collection:          AppBundle\Entity\Classification\Collection

  #==================================================================
  # Entity Manager
  #==================================================================
  manager_class:
    orm:
      media:   'Rz\MediaBundle\Entity\MediaManager'
      gallery: 'Rz\MediaBundle\Entity\GalleryManager'

  #==================================================================
  # Admin
  #==================================================================
  admin:
    media:
      class:        'Rz\MediaBundle\Admin\ORM\MediaAdmin'
      controller:   'RzMediaBundle:MediaAdmin'
      translation:  'SonataMediaBundle'

    gallery:
      class:        'Rz\MediaBundle\Admin\ORM\GalleryAdmin'
      controller:   'RzMediaBundle:GalleryAdmin'
      translation:  'SonataMediaBundle'

    gallery_has_media:
      class:        'Rz\MediaBundle\Admin\ORM\GalleryHasMediaAdmin'
      controller:   'SonataAdminBundle:CRUD'
      translation:  'SonataMediaBundle'


  #==================================================================
  # Providers Configuration
  #==================================================================
  providers:
    gallery:
      # Default Media Context
      default_context: gallery # gallery context must be present
      # Default Collection
      default_collection: default
      # Default provider collection
      default_provider_collection: default
      # GalleryHasMedia default settings
      media_lookup_settings:
        hide_context: false
        default_context: default
        default_category: default
      collections:
          default:  # the default context is mandatory
            gallery:
              provider: rz.media.gallery_provider.default
              # GalleryHasMedia settings
              media_lookup_settings:
                hide_context: true
                context: news
                category: blog
            gallery_has_media:
              provider: rz.media.gallery_has_media_provider.default

  #==================================================================
  # Blocks
  #==================================================================
  blocks:
    media:
      # Override Class
      #class: Rz\MediaBundle\Block\MediaBlockService
      # Block Templates
      templates:
        media_block:
          name: Default
          path: RzMediaBundle:Block:media.html.twig
