##############################################################################
# Sonata Classification
##############################################################################
sonata_classification:
    class:
        tag:            AppBundle\Entity\Classification\Tag
        category:       AppBundle\Entity\Classification\Category
        context:        AppBundle\Entity\Classification\Context
        collection:     AppBundle\Entity\Classification\Collection
        media:          AppBundle\Entity\Media\Media

    admin:
        tag:
            class:      AppBundle\Admin\Classification\TagAdmin
            controller: RzClassificationBundle:TagAdmin
        category:
            class:      AppBundle\Admin\Classification\CategoryAdmin
            controller: RzClassificationBundle:CategoryAdmin
        context:
            class:      AppBundle\Admin\Classification\ContextAdmin
        collection:
            class:      AppBundle\Admin\Classification\CollectionAdmin
            controller: RzClassificationBundle:CollectionAdmin

##############################################################################
# RzClassification
##############################################################################
rz_classification:
  manager_class:
    orm:
      tag:        'Rz\ClassificationBundle\Entity\TagManager'
      category:   'Rz\ClassificationBundle\Entity\CategoryManager'
      collection: 'Rz\ClassificationBundle\Entity\CollectionManager'
      context:    'Rz\ClassificationBundle\Entity\ContextManager'

  #=====================================================================
  # Bundle Default Settings
  #=====================================================================
  settings:
    category:
      default_context: 'news' # NOTE: default context used for grouping tag, media, ckeditor_context, collection
    collection:
      default_context: 'news' # NOTE: default context used for grouping tag, media, ckeditor_context, collection
    tag:
      default_context: 'news' # NOTE: default context used for grouping tag, media, ckeditor_context, collection

  #=====================================================================
  # PROVIDERS Configuration
  #   provider are classes that allows programatically adding
  #   new fields on the classification modules
  #=====================================================================
  providers:
    #----------------------------------------------------------------------------------------
    # Providers and Pool class override - SAMPLE with default classes
    #----------------------------------------------------------------------------------------
    #class:
    #  pool:
    #    category:    'Rz\ClassificationBundle\Provider\Category\Pool'
    #    collection:  'Rz\ClassificationBundle\Provider\Collection\Pool'
    #    tag:         'Rz\ClassificationBundle\Provider\Tag\Pool'
    #  default_provider:
    #    category:    'Rz\ClassificationBundle\Provider\Category\DefaultProvider'
    #    collection:  'Rz\ClassificationBundle\Provider\Collection\DefaultProvider'
    #    tag:         'Rz\ClassificationBundle\Provider\Tag\DefaultProvider'

    #----------------------------------------------------------
    # Category Provider
    #----------------------------------------------------------
    category:
      context:
          default:  # the default context optional
              provider: rz.classification.category.provider.default

    #----------------------------------------------------------
    # Category Provider
    #----------------------------------------------------------
    collection:
      context:
          default:  # the default context optional
              provider: rz.classification.collection.provider.default

    #----------------------------------------------------------
    # Category Provider
    #----------------------------------------------------------
    tag:
      context:
          default:  # the default context optional
              provider: rz.classification.tag.provider.default

##############################################################################
# Classification Doctrine
##############################################################################
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataClassificationBundle: ~
