##############################################################################
# Sonata Classification
##############################################################################
sonata_classification:
    class:
        tag:            AppBundle\Entity\Classification\Tag
        category:       AppBundle\Entity\Classification\Category
        context:        AppBundle\Entity\Classification\Context
        collection:     AppBundle\Entity\Classification\Collection
        media:          AppBundle\Entity\Media\Media

    admin:
        tag:
            class:      AppBundle\Admin\Classification\TagAdmin
            controller: RzClassificationBundle:TagAdmin
        category:
            class:      AppBundle\Admin\Classification\CategoryAdmin
            controller: RzClassificationBundle:CategoryAdmin
        context:
            class:      AppBundle\Admin\Classification\ContextAdmin
        collection:
            class:      AppBundle\Admin\Classification\CollectionAdmin
            controller: RzClassificationBundle:CollectionAdmin

##############################################################################
# RzClassification
##############################################################################
rz_classification:
  manager_class:
    orm:
      tag:        'Rz\ClassificationBundle\Entity\TagManager'
      category:   'Rz\ClassificationBundle\Entity\CategoryManager'
      collection: 'Rz\ClassificationBundle\Entity\CollectionManager'
      context:    'Rz\ClassificationBundle\Entity\ContextManager'

  #=====================================================================
  # PROVIDERS Configuration
  #   provider are classes that allows programatically adding
  #   new fields on the classification modules
  #=====================================================================
  providers:

    #----------------------------------------------------------
    # Category Provider
    #----------------------------------------------------------
    category:
      default_context: 'news' # NOTE: default context used for grouping tag, media, ckeditor_context, collection
      default_provider_context: default # NOTE: default provider - provider are classes that allows programatically adding new fields on the POST table
      context:
          default:  # the default context is mandatory (fallback provider when no other provider is set)
              provider: rz.classification.category.provider.default

    #----------------------------------------------------------
    # Category Provider
    #----------------------------------------------------------
    collection:
      default_context: 'news' # NOTE: default context used for grouping tag, media, ckeditor_context, collection
      default_provider_context: default # NOTE: default provider - provider are classes that allows programatically adding new fields on the POST table
      context:
          default:  # the default context is mandatory (fallback provider when no other provider is set)
              provider: rz.classification.collection.provider.default

    #----------------------------------------------------------
    # Category Provider
    #----------------------------------------------------------
    tag:
      default_context: 'news' # NOTE: default context used for grouping tag, media, ckeditor_context, collection
      default_provider_context: default # NOTE: default provider - provider are classes that allows programatically adding new fields on the POST table
      context:
          default:  # the default context is mandatory (fallback provider when no other provider is set)
              provider: rz.classification.tag.provider.default

##############################################################################
# Classification Doctrine
##############################################################################
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataClassificationBundle: ~
