##############################################################################
# User Doctrine
##############################################################################
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    RzOAuthServerBundle: ~
                    FOSOAuthServerBundle: ~

rz_oauth_server: ~